### ISSUE TITLE
Can't build on macOS because `nix::unistd::daemon` doesn't exist

### ISSUE THREAD

**Issue by samuelstevens** [ltratt/pizauth#3]
I don't think this is easily fixable, but I am building on macOS and get:

```
error[E0432]: unresolved import `nix::unistd::daemon`
```

I assume this is because `dameon` is not included in `nix::unistd` on macOS (as per [this line](https://github.com/nix-rust/nix/blob/3f637de8e027843e1b2c4e9a05f19b071ea00017/src/unistd.rs#L968)). I am not a Rust programmer; are there any quick fixes I could make on macOS to solve this?

Thanks

**Comment by ltratt** [comment]
I know very little about OS X, but a quick search suggests:

1. OS X does have the `daemon` function https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/daemon.3.html
2. nix doesn't include `darwin` in the guard (i.e. won't compile it on OS X) https://docs.rs/nix/0.25.0/src/nix/unistd.rs.html#960

The right fix is to file a PR against nix adding `darwin` to the list of OSs that support `daemon`. I'd encourage you to give that a go, as it should be pretty obvious if it compiles and links on OS X, and then future versions of nix (and pizauth) will "just work (TM)".

The horrible hack (untested, unsupported) is to comment out `use nix::unistd::daemon;` and the `daemon(true, false).unwrap_or_else(|e| fatal(&format!("Cannot daemonise: {e:}")));` line *and* to call `pizauth server -d` so that it doesn't immediately exit.

**Comment by samuelstevens** [comment]
No kidding, `man daemon` works on my machine. I'll fork nix, make the change, recompile and see if it all works. Not having extensively written any Rust before, does [this stackoverflow answer](https://stackoverflow.com/questions/33025887/how-to-use-a-local-unpublished-crate) seem like a reasonable way to use my own fork of nix to build pizauth?

**Comment by ltratt** [comment]
In terms of nix itself I would think that even just `cargo build` is a sufficient test (if, by some miracle, OS X is lying about having `daemon` then `cargo build` will fail at link time). If you want to test it with pizauth then load pizauth's `Cargo.toml` and change the `nix` line to something like `nix = { path="/path/to/local/nix" }` and it should compile pizauth with your locally altered nix. Best of luck!

**Comment by eddieantonio** [comment]
> 1. OS X does have the `daemon` function https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/daemon.3.html

...but it's deprecated. Here's me trying to compile a C program that uses it:

```
$ clang -Wall use_daemon.c
use_daemon.c:4:5: warning: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
    daemon(0, 0);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:294:6: note: 'daemon' has been explicitly marked deprecated here
int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
1 warning generated.
```

(macOS 10.5 was [released in 2007](https://en.wikipedia.org/wiki/Mac_OS_X_Leopard#:~:text=leopard%20was%20released%20on%20october%2026%2C%202007) 🤯)

AS a result, it's [hidden in the `libc` crate](https://github.com/rust-lang/libc/blob/96c85c1b913604fb5b1eb8822e344b7c08bcd6b9/src/unix/bsd/apple/mod.rs#L5064-L5067): 

```rust
    #[doc(hidden)]
    #[deprecated(since = "0.2.49", note = "Deprecated in MacOSX 10.5")]
    #[cfg_attr(not(target_arch = "aarch64"), link_name = "daemon$1050")]
    pub fn daemon(nochdir: ::c_int, noclose: ::c_int) -> ::c_int;
```

> The right fix is to file a PR against nix adding `darwin` to the list of OSs that support `daemon`. I'd encourage you to give that a go, as it should be pretty obvious if it compiles and links on OS X, and then future versions of nix (and pizauth) will "just work (TM)".

Trying to do this will cause `nix` to emit the `deprecated()` warning above:

```
error: use of deprecated function `libc::daemon`: Deprecated in MacOSX 10.5
   --> src/unistd.rs:970:30
    |
970 |     let res = unsafe { libc::daemon(nochdir as c_int, noclose as c_int) };
    |                              ^^^^^^
    |
note: the lint level is defined here
   --> src/lib.rs:46:24
    |
46  | #![cfg_attr(test, deny(warnings))]
    |                        ^^^^^^^^
    = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`

error: could not compile `nix` due to previous error
```

macOS wants you to use [`posix_spawn(3)`](https://man7.org/linux/man-pages/man3/posix_spawn.3.html) instead of `daemon(3)`, but I believe support for it in `nix` is an open issue: https://github.com/nix-rust/nix/issues/1740

---

So no quick and easy fix for this, unfortunately :/

**Comment by ltratt** [comment]
It might be, perhaps, that nix will refuse to support `daemon` on OS X. If so, I could live with a local "compiled only on OS X" version in pizauth (in a `compat/` directory).  [I must admit that I'd be surprised if OS X actually gets rid of `daemon` any time soon -- it's still a common function.] I've never used `posix_spawn` and the API is very general and slightly scary! But if someone proposed using `posix_spawn` (perhaps even via `libc`) I would be open-minded about including it.

**Comment by ltratt** [comment]
@samuelstevens Try now -- @eddieantonio has kindly fixed things!

**Comment by samuelstevens** [comment]
Great! It does build for me now on macOS and successfully runs. Unfortunately I cannot create a conf file that fools my organizations OAuth2 server. Maybe I will be able to use this for a different OAuth application later on!
